services:
  app:
    image: rustam2/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: blog-test
    working_dir: /app
    environment:
      - NODE_ENV=test
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    command: make test

  db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
