services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-test
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=test
    command: make test
